"""Fourth Migration

Revision ID: 1ebba01dd121
Revises: dbe166765d00
Create Date: 2022-05-19 11:25:53.846458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ebba01dd121'
down_revision = 'dbe166765d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post', sa.Text(), nullable=True))
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'post')
    # ### end Alembic commands ###
