"""Fourth Migration

Revision ID: 67144e60dd3b
Revises: 1ebba01dd121
Create Date: 2022-05-19 11:32:32.746762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67144e60dd3b'
down_revision = '1ebba01dd121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('posts_poster_id_fkey', 'posts', type_='foreignkey')
    op.drop_constraint('posts_category_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    op.drop_column('posts', 'poster_id')
    op.drop_column('posts', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('poster_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_category_id_fkey', 'posts', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('posts_poster_id_fkey', 'posts', 'users', ['poster_id'], ['id'], ondelete='CASCADE')
    op.drop_column('posts', 'user_id')
    # ### end Alembic commands ###
