"""Third Migration

Revision ID: c91acfc5dfa3
Revises: eec7f95e218a
Create Date: 2022-05-18 15:51:16.054486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91acfc5dfa3'
down_revision = 'eec7f95e218a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'firstname')
    op.drop_column('users', 'lastname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastname', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('firstname', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
