"""THird Migration

Revision ID: dbe166765d00
Revises: 93e31a10ea81
Create Date: 2022-05-19 11:22:41.186387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe166765d00'
down_revision = '93e31a10ea81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('username', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('category', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_posts_category'), 'posts', ['category'], unique=False)
    op.create_index(op.f('ix_posts_username'), 'posts', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_username'), table_name='posts')
    op.drop_index(op.f('ix_posts_category'), table_name='posts')
    op.drop_column('posts', 'category')
    op.drop_column('posts', 'username')
    # ### end Alembic commands ###
