"""Second Migration

Revision ID: eec7f95e218a
Revises: a9b82bcbc01c
Create Date: 2022-05-18 15:28:23.140393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec7f95e218a'
down_revision = 'a9b82bcbc01c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=200), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
